### ISSUE TITLE
web_pic_gradient

### ISSUE THREAD

**Issue by inioslawa** [ncsu-osgeorel/uav-lidar-analytics-course#2]
![wbb_pic](https://cloud.githubusercontent.com/assets/11337506/7071899/3b407f66-deb6-11e4-951b-c4f0bccd1d03.png)

**Comment by wenzeslaus** [comment]
If this is new suggestion for the header image, it should be part of #1.

**Comment by wenzeslaus** [comment]
Header images cleaned up in 60d11c.
