### ISSUE TITLE
web_pic_gradient2

### ISSUE THREAD

**Issue by inioslawa** [ncsu-osgeorel/uav-lidar-analytics-course#3]
![web_pic](https://cloud.githubusercontent.com/assets/11337506/7071928/74717812-deb6-11e4-973b-d037df23144e.png)

**Comment by wenzeslaus** [comment]
If this is new suggestion for the header image, it should be part of #1. Now please link this and #2 issue in #1.

**Comment by wenzeslaus** [comment]
Header images cleaned up in 60d11c.
